# Generated by Django 4.2.7 on 2026-01-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ingredients/'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='nutritional_info',
            field=models.TextField(blank=True, help_text='Nutritional information per 100g'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='organic',
            field=models.BooleanField(default=False, help_text='Is this ingredient organic?'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='origin',
            field=models.CharField(blank=True, help_text='Origin/source of the ingredient', max_length=200),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='seasonal',
            field=models.BooleanField(default=False, help_text='Is this ingredient seasonal?'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='supplier',
            field=models.CharField(blank=True, help_text='Supplier name', max_length=200),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='model_3d',
            field=models.FileField(blank=True, help_text='3D model file (.glb, .gltf, .obj)', null=True, upload_to='menu_3d/'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='video',
            field=models.FileField(blank=True, help_text='Video of the dish being prepared or presented', null=True, upload_to='menu_videos/'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='video_thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail for video', null=True, upload_to='menu_thumbnails/'),
        ),
    ]
