# Generated by Django 4.2.7 on 2026-01-29 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_ingredient_image_ingredient_nutritional_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='branches/')),
                ('opening_hours', models.TextField(blank=True, help_text='Opening hours for this branch')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='review',
            name='category',
            field=models.CharField(choices=[('branch', 'Branch/Location'), ('service', 'Service/Staff'), ('product', 'Product/Food'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='menu_item',
            field=models.ForeignKey(blank=True, help_text='Only for product reviews', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='menu.menuitem'),
        ),
        migrations.AddField(
            model_name='review',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Only for branch reviews', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='menu.branch'),
        ),
    ]
